### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by tunix** [pop-os/desktop-widget#28]
I'd like to take this opportunity to thank you for enabling us to configure more of our desktop experience without having to install arbitrary extensions.
I use my desktop environment in Turkish language. There seems to be a few problems in GNOME Settings in terms of i18n and there is no translation at all inside Desktop menu.
I checked the source code but couldn't find anything that may be the starting point for the translation part. Unfortunetely I'm not able to write Rust atm. (I also don't know about various GTK related stuff that I saw inside the code which makes it a lot harder)
I guess there is no translation support at the moment but if you happen to be providing the translation files, I'd more than happy to translate it into Turkish. Thanks!

**Comment by ids1024** [comment]
Closing, since desktop-widget now has localization support and a couple transations (in the [i18n directory](https://github.com/pop-os/desktop-widget/tree/master_hirsute/i18n)).
