### ISSUE TITLE
With this, appearance panel can't shrink to too narrow a width

### ISSUE THREAD

**Issue by ids1024** [pop-os/desktop-widget#3]
I noted this wasn't working quite correctly. When the window is make too narrow, Gnome Control Center collapses the panel and shows the list of panel, and when switching back to the Appearance panel, it can't shrink as narrow as most panels.

After some testing, it seems the `GtkStackSwitcher` in the title bar is the cause. Not sure what alternative would be better here.

**Comment by jackpot51** [comment]
That was used to match the previous design of that page. Which doesn't work that well for numerous reasons, one being that the order of the stack items could not match the design without significant work.

**Comment by isantop** [comment]
Perhaps changing the stack switcher for this LibHandy widget? It would allow the switcher to move/shrink depending on window width. 

![image](https://user-images.githubusercontent.com/5883565/113790076-c02d0400-96fd-11eb-874f-5b1cac292296.png)

**Comment by ids1024** [comment]
Interesting `HdyViewSwitcher` has a slightly different style, and is a bit narrower; not much of a change.

![Screenshot from 2021-04-13 09-52-39](https://user-images.githubusercontent.com/2263150/114591307-9bc1b200-9c3e-11eb-81aa-e07d56b1d765.png)
![Screenshot from 2021-04-13 09-52-06](https://user-images.githubusercontent.com/2263150/114591313-9cf2df00-9c3e-11eb-9ca3-35f4836959a3.png)

> It would allow the switcher to move/shrink depending on window width.

`HdyViewSwitcherTitle` is designed to display as a `HdyViewSwitcher`, or if too narrow show the title (and a switcher can be shown elsewhere). But testing it, while the panel can get narrower, Gnome Control Center still seems to collapse the window so the panel list and contents of the panel show on separate pages. So it doesn't really seem to fix the issue unless there's a way to change that.

It may be worth considering another design. The "Applications" and "Privacy" panels instead list their subsections in the sidebar. The way this behaves isn't entirely ideal though, and the Design Team isn't entirely happy with it either.

**Comment by WatchMkr** [comment]
The navigation for "Desktop" should move to the Privacy panel style.

**Comment by ids1024** [comment]
> The navigation for "Desktop" should move to the Privacy panel style.

Implemented in https://github.com/pop-os/gnome-control-center/pull/161:

![Screenshot from 2021-04-14 11-58-38](https://user-images.githubusercontent.com/2263150/114764410-c3854880-9d18-11eb-8795-b09ed420b719.png)

**Comment by jackpot51** [comment]
@ids1024 we'd also like to make Desktop come first, Background second, I believe
