### ISSUE TITLE
When opened in G-C-C, the window cannot shrink to a manageable height

### ISSUE THREAD

**Issue by isantop** [pop-os/desktop-widget#4]
I haven't measured the exact size, but when the Appearance section is focused in Settings, the window grows to extraordinary size and cannot be shrunk to a more normal size. I believe putting the window contents into a ScrolledWindow would probably fix this issue. 

![image](https://user-images.githubusercontent.com/5883565/113789717-eb632380-96fc-11eb-9e3c-528fdbcb1c5f.png)

This window does not fit on a 1920x1080p monitor, and hides the dock placement settings from view entirely unless the user drags the window up with Super+Click (and knows about this functionality).

**Comment by ids1024** [comment]
I have a fix for this using a `GtkScrolledWindow` in https://github.com/pop-os/desktop-widget/tree/desktop-widget-updates_hirsute
