### ISSUE TITLE
Super key does not open launcher in VM

### ISSUE THREAD

**Issue by joeljosedev** [pop-os/desktop-widget#78]
### When setting the Super Key Action to `Launcher`, nothing happens when it is pressed.

![Screenshot from 2022-01-07 21-58-05](https://user-images.githubusercontent.com/53969297/148575038-10d44937-3238-4336-903f-3cfc413dbd8f.png)

# Pop!_OS Info

```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**Comment by mmstick** [comment]
Do you have the pop-shell extension enabled? What logs do you get from `journalctl -f /usr/bin/gnome-shell` when you press the super key?

**Comment by joeljosedev** [comment]
Sorry, the pop-shell extension was disabled on my VM. Enabling it fixed the issue.
