### ISSUE TITLE
Custom dock size loses focus when size matches other options

### ISSUE THREAD

**Issue by bflanagin** [pop-os/desktop-widget#8]
When using the custom size option for the dock the radio button jumps from "custom" to the appropriate size if the number in the spin button is the same as one of the defaults. This loss of focus feels wrong even if its technically kind of cool.

To witness the issue simple pick one of the smaller sizes for the doc. Then select custom and go up to the next available size using the spin button. You will lose focus at the moment you hit the next options size and must click custom again to continue. 

In some ways I like the interaction with the user, but if this is on purpose instead of a bug maybe we can change the font of the non-custom option instead of pulling the users away from the option they are currently on?

**Comment by ids1024** [comment]
Hm, definitely doesn't seem great the way it currently works. Particularly how changing the spinbutton can make it insensitive. Internally in gsettings the setting is just a numerical value.

Perhaps the spin button could always be sensitive, and "custom" automatically selected when a value other than one of the options is selected... though manually selecting "custom" would then be redundant, which is a bit weird.

I wonder if there's anywhere Gnome offers a couple settings plus a "custom" option like this. That might help to show how it can best be done in gtk.

**Comment by ids1024** [comment]
Resolved in https://github.com/pop-os/desktop-widget/pull/12. (Unless someone can come up with an even better solution). Closing.
