### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/desktop-widget#91]
On 22.04, I don't see any translations showing up. For example, trying to test https://github.com/pop-os/desktop-widget/pull/90, I installed that branch, created a new user via G-C-C, set the new user's account to French via the Users panel in G-C-C, and logged in with that user. I see some strings translated (such as the name of the section in the sidebar), but the strings within the page are not translated:

![Screenshot from 2022-04-11 11-11-32](https://user-images.githubusercontent.com/7199422/162793956-4288c960-e5dd-48f5-9e8a-0cbcaf231939.png)

The same thing is happening in 21.10 with the Polish translation from https://github.com/pop-os/desktop-widget/pull/89:

![image](https://user-images.githubusercontent.com/7199422/162796092-d298893c-4062-4d40-850a-e82c1bbf0498.png)

**Comment by jacobgkau** [comment]
If I change the `fallback_language` in `i18n.toml`, then whatever I set as the fallback language does show up, which seems to indicate that the translation files themselves have valid syntax.

**Comment by mmstick** [comment]
It may be that the C library isn't calling the `init()` function which detects the system language and loads the definitions for it.
